Endpoint details pinia store
Particular/ServicePulse pull request #1658
Opened 2023-12-20 23:00 UTC by soujay

Add Pinia store to the endpoint details page in order to retrieve the following 
- Endpoint details
- Failed messages count 

The PR also has added the option to retrieve the disconnected endpoint count

2024-01-04 20:23 UTC, cquirosj commented on src/ServicePulse.Host/vue/src/components/monitoring/EndpointDetails.vue
> +        updateUI();
Shouldn't this function call use await?

2024-01-05 21:11 UTC, cquirosj requested changes

2024-01-05 21:11 UTC, cquirosj commented on src/ServicePulse.Host/vue/src/components/monitoring/EndpointDetails.vue
> +        updateUI();
```suggestion
        await updateUI();
```

2024-01-09 22:09 UTC, TravisNickels approved these changes

2024-01-09 22:10 UTC, merged