[WIP] Migrate to async
Particular/ServicePulse pull request #1666
Opened 2024-01-12 02:53 UTC by mikeminutillo

Migrate promises code to async.

Requires thorough testing.

2024-01-22 00:19 UTC, johnsimons requested changes
I added the following eslint rule, and there were some errors @mikeminutillo 
<img width="1038" alt="image" src="https://github.com/Particular/ServicePulse/assets/122651/247f12c1-460d-47a1-a82e-b35d7af7177e">

2024-01-22 00:19 UTC, johnsimons commented on src/ServicePulse.Host/vue/src/components/failedmessages/AllDeletedMessages.vue
`loadMessages` does not seem to be awaited anywhere, is this right?

2024-01-22 00:19 UTC, johnsimons commented on src/ServicePulse.Host/vue/src/components/failedmessages/AllFailedMessages.vue
same as before `loadMessages` not awaited

2024-01-22 00:33 UTC, johnsimons requested changes
I decided to install https://github.com/SebastienGllmt/eslint-plugin-no-floating-promise. This is one of the rules we need to enforce the proper `await/async`.
After enabling it and running the lint, it seems we have a few missing awaits!
<img width="1078" alt="image" src="https://github.com/Particular/ServicePulse/assets/122651/dbabdf3e-4d53-4e07-8739-71502d131903">

2024-01-22 00:33 UTC, johnsimons commented on src/ServicePulse.Host/vue/src/components/failedmessages/LastTenOperations.vue
> +async function getHistoricOperations() {
not awaited

2024-01-29 01:15 UTC, johnsimons approved these changes

2024-01-29 01:19 UTC, PhilBastian approved these changes

2024-01-29 01:57 UTC, johnsimons approved these changes

2024-01-30 08:31 UTC, merged