Elastic scale patch
Particular/ServicePulse pull request #2056
Opened 2024-09-12 08:04 UTC by PhilBastian

fix results count not showing and enable deletion of non-tracked endpoints

2024-09-12 08:32 UTC, johnsimons commented on src/Frontend/src/components/heartbeats/HealthyEndpoints.vue
> +import ResultsCount from "../ResultsCount.vue";
This is really weird, how come this did not break the build?

2024-09-12 08:38 UTC, johnsimons requested changes

2024-09-12 08:38 UTC, johnsimons commented on src/Frontend/src/components/heartbeats/EndpointInstances.vue
> +    useShowToast(TYPE.SUCCESS, "Endpoint instance deleted", "", false, { timeout: 1000 });
Should this say
```suggestion
    useShowToast(TYPE.SUCCESS, "Endpoint deleted", "", false, { timeout: 1000 });
```

2024-09-12 22:23 UTC, johnsimons requested changes
I have tested this and a few things that don't look right.
- I think the "delete button" should have a warning dialog given it is a dangerous action, thoughts?
- When the deletion occurs, we get multiple toasters, I assume one per instance, to me it would make more sense to be a single toaster

2024-09-12 22:59 UTC, PhilBastian commented
> I have tested this and a few things that don't look right.
> 
> * I think the "delete button" should have a warning dialog given it is a dangerous action, thoughts?
> * When the deletion occurs, we get multiple toasters, I assume one per instance, to me it would make more sense to be a single toaster

the other delete buttons don't give a warning
there should only be one toast message. I wonder if it's something to do with the route change?

2024-09-12 23:19 UTC, johnsimons commented
> the other delete buttons don't give a warning

the others are single this one is bulk delete

2024-09-13 00:29 UTC, johnsimons approved these changes
I don't think we need the warning dialog for delete endpoint.

2024-09-13 00:59 UTC, merged