Select all messages and toggle if messages are selected
Particular/ServicePulse pull request #947
Opened 2020-10-09 19:48 UTC by seanfarmar

related to #639

2020-10-12 16:00 UTC, timbussmann reviewed
some ideas to consider

2020-10-12 16:00 UTC, timbussmann commented on src/ServicePulse.Host/app/js/views/failed_messages/controller.js
> +                    vm.selectedIds.indexOf(item.id) >= 0 ? false : vm.selectedIds.push(item.id);
if we clear the `selectedIds` collection before looping through `failedMessages`, shouldn't this ensure that `vm.selectedIds.indexOf(item.id) >= 0` is never true and we could just push without checking?

2020-10-13 08:22 UTC, sergioc requested changes
Ideally I'd prefer a checkbox instead of a button to stick to conventions, but for now let's roll with the button for the sake of simplicity. 

Only the label `Select None` should be renamed to `Clear selection`.

2020-10-16 11:28 UTC, sergioc approved these changes

2020-10-16 11:54 UTC, timbussmann approved these changes

2020-10-16 11:56 UTC, merged